var quotes = ["THERE IS ONLY ONE HAPPINESS IN THIS LIFE, TO LOVE AND BE LOVED.",
"LIFE IS 10% WHAT HAPPENS TO YOU AND 90% HOW YOU REACT TO IT.",
"ONLY I CAN CHANGE MY LIFE. NO ONE CAN DO IT FOR ME.",
"THE GREATEST GIFT OF LIFE IS FRIENDSHIP, AND I HAVE RECEIVED IT.",
"MY MISSION IN LIFE IS NOT MERELY TO SURVIVE, BUT TO THRIVE; AND TO DO SO WITH SOME PASSION, SOME COMPASSION, SOME HUMOR, AND SOME STYLE.",
"DO NOT TAKE LIFE TOO SERIOUSLY. YOU WILL NEVER GET OUT OF IT ALIVE.",
"LIVE LIFE TO THE FULLEST, AND FOCUS ON THE POSITIVE.",
"DO NOT DWELL IN THE PAST, DO NOT DREAM OF THE FUTURE, CONCENTRATE THE MIND ON THE PRESENT MOMENT.",
"BUT MAN IS NOT MADE FOR DEFEAT. A MAN CAN BE DESTROYED BUT NOT DEFEATED. -- ERNEST HEMINGWAY",
"KEEP YOUR FACE ALWAYS TOWARD THE SUNSHINE - AND SHADOWS WILL FALL BEHIND YOU. --WALT WHITMAN",
"THERE ARE TWO WAYS OF SPREADING LIGHT: TO BE THE CANDLE OR THE MIRROR THAT REFLECTS IT. -- EDITH WHARTON",
"NOT ALL THOSE WHO WANDER ARE LOST. --J. R. R. TOLKIEN"]

function newQuote(){
	var curQuote = quotes[Math.floor(Math.random() * quotes.length)];
	document.getElementById("quoteDisplay").innerHTML = curQuote;
	$('#tweetQuote').attr('href', 'https://twitter.com/intent/tweet?text='+curQuote).attr('target', '_blank');
}
